### ISSUE TITLE
Do not react on Spotify notifications

### ISSUE THREAD

**Issue by khvMX** [hackedbellini/gnome-shell-notifications-alert#23]
"If you find any other any other weird behavior like that, please, file an issue here providing the name of the program in question that generated the notification."
Here you are: Spotify notifies about every started song, and triggers the alert. Would be nice to not to react on such notifications.

**Comment by hackedbellini** [comment]
hrmm, thanks for the report! As soon as I have some time, I'll try to fix this together with #24

**Comment by hackedbellini** [comment]
This was probably fixed by https://github.com/hackedbellini/gnome-shell-notifications-alert/pull/26
