### ISSUE TITLE
Blacklist app that is not in the list

### ISSUE THREAD

**Issue by qfvldaa2xn** [hackedbellini/gnome-shell-notifications-alert#37]
First I would like to thank you for this nice extension! Very much like it :)

I was wondering how to blacklist an app that is not in the list of applications when clicking 'Add Rule'.
In my case the offical dropbox client always notifies me when someone changes a file.
But dropbox does not appear in the list. So is there a way to add it manually?

**Comment by qfvldaa2xn** [comment]
I found the key in dconf:
/org/gnome/shell/extensions/notifications-alert/application-list

When adding ['dropbox.desktop'] it works.
Issue closed :)

**Comment by hackedbellini** [comment]
@qfvldaa2xn glad you solved it. Feel free to open more issues for any other problem you find! :)
