### ISSUE TITLE
Alert from Mailnag only

### ISSUE THREAD

**Issue by sojusnik** [hackedbellini/gnome-shell-notifications-alert#9]
Hi,

is there an option to enable your extension to react only on Mailnag alerts? 

A switchable option for Mailnag alerts would therefore be great, like we already have with chat notifications. Even better would be a list where we could specify, what programs should trigger the alert.

What do you think about it?

Bye!

**Comment by hackedbellini** [comment]
Does this solve the issue for you? https://github.com/hackedbellini/gnome-shell-notifications-alert/pull/26

Sure, it is not the "whitelist" approach you were asking for, but it could be something.
